# "version" option of the pip module doesn't work with URLs
---
- name: Install sensors exporter package with pip
  pip:
    name: "git+{{ sensors_exporter_src }}@{{ sensors_exporter_version }}"
  become: true
  notify: Sensors Exporter Service

