---
- name: Create sensors exporter environment file
  ansible.builtin.template:
    src: environment.j2
    dest: /etc/default/sensors-exporter
  become: true

- name: Create systemd service file
  ansible.builtin.template:
    src: sensors_exporter_service.j2
    dest: /etc/systemd/system/sensors-exporter.service
  become: true
  notify: Sensors Exporter Service

